mongo:
  databaseName: hubNotifications

grpc:
 port: 7777
 servercertfile: cert/server-cert.pem
 serverkeyfile: cert/server-key.pem
 clientcacertfile: cert/ca-cert.pem
 clinetkeyfile: cert/client-key.pem
 clinetcertfile: cert/client-cert.pem

